# Generated by Django 5.1.4 on 2025-01-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
